added `wipe` make command
imartinez/privateGPT pull request #1215
Opened 2023-11-12 14:06 UTC by domx4q

As suggested in the README.md file, I've added the wipe command to clear the `local_data` folder.

2023-11-14 15:39 UTC, imartinez requested changes
Code changes LGTM! 

Pending to migrate:
- Document the new command it in docs/description.md (I think the section ### Reset Local documents database would be the one to update)
- After changing the documentation, run `make api-docs` and commit the generated changes - it is the way to publish the changes in the documentation.

2023-11-14 18:09 UTC, domx4q commented
I've added the command to the description.md file and ran the `make api-docs` command. Now there are some changes in the openapi.json file where I'm not sure if it should be so.

2023-11-14 20:12 UTC, domx4q commented on docs/openapi.json
I've rebased and there are still this weird changes like in line 394. But I think its just a new formating. But I wasn't sure.

2023-11-14 20:18 UTC, imartinez approved these changes

2023-11-15 10:12 UTC, lopagela approved these changes
Good to go - openapi documentation have been also updated after my changes to get rid of `enum` kwargs passed to extensions of `BaseModel`

Good to go!

2023-11-15 10:14 UTC, lopagela commented
I restarts the CICD checks on the commit as there seems to be a glitch preventing the merging of this PR.

2023-11-15 13:29 UTC, domx4q commented
> I restarts the CICD checks on the commit as there seems to be a glitch preventing the merging of this PR.

I think it's stuck again. I can't see all you repo settings, maybe this article could help.
https://github.com/orgs/community/discussions/26698

2023-11-16 10:43 UTC, lopagela commented
> > I restarts the CICD checks on the commit as there seems to be a glitch preventing the merging of this PR.
> 
> I think it's stuck again. I can't see all you repo settings, maybe this article could help. https://github.com/orgs/community/discussions/26698

Thank you @domx4q ! That was indeed the root cause 😉 

Feel free to come and say hi in the discord of this project, [channel](https://discord.com/channels/1164200432894234644/1167405247140986901) `#contributors`

2023-11-16 10:44 UTC, merged