Allow setting OpenAI model in settings
imartinez/privateGPT pull request #1386
Opened 2023-12-08 21:33 UTC by 3ly-13

This PR allows setting the Open AI model to use in settings as proposed here https://github.com/users/imartinez/projects/3?pane=issue&itemId=44266044.

2023-12-08 22:25 UTC, imartinez requested changes
Let's also include this information in the docs, in fern/docs/pages/manual/llms.mdx

2023-12-08 22:25 UTC, imartinez commented on settings.yaml
> +  model: gpt-4
I'd default to "gpt-3.5-turbo" in this settings.yaml, given it is the one being used by most people.

2023-12-09 18:20 UTC, 3ly-13 commented
I ran `make check` and no issues were identified for this PR. @imartinez when you have a chance, please review. Thanks!

2023-12-09 18:40 UTC, imartinez approved these changes

2023-12-09 19:13 UTC, merged