using `make setup` instead of poetry
imartinez/privateGPT pull request #1391
Opened 2023-12-10 18:37 UTC by Muxelmann

2023-12-15 20:27 UTC, lopagela approved these changes

2023-12-16 17:28 UTC, imartinez commented
`make` is an optional dependency, so we should keep in the documentation the fallback to using `poetry run python scripts/setup`

2023-12-16 17:29 UTC, imartinez requested changes
make is an optional dependency, so we should keep in the documentation the fallback to using poetry run python scripts/setup

2024-03-11 21:57 UTC, imartinez commented
Does not apply to the new docs. Please reopen adapting to the new docs. Thanks!

2024-03-11 21:57 UTC, closed without merging