Fixes
imartinez/privateGPT pull request #1963
Opened 2024-06-06 19:46 UTC by hirschrobert

see commits

2024-07-04 14:50 UTC, jaluma requested changes

2024-07-04 14:50 UTC, jaluma commented on private_gpt/settings/settings.py
> +    )
Can you move this property to another setting? It would be nice if we have different providers like graphs, elastic search, etc.

2024-07-04 14:50 UTC, jaluma commented on settings.yaml
> +  inject_win_size: 2
Please remove this line or set default value

2026-05-29 10:51 UTC, AlfonsoLozana commented
Thank you for your contribution!
We consider this PR valuable, but we're doing a major update to the repository and unfortunately these changes no longer apply to the current codebase. For that reason, we're closing it, but please feel free to open it again over the new codebase, we'd love to review it there. 
We really appreciate the time and effort you put into this, and hope you'll continue being part of the project!

2026-05-29 10:51 UTC, closed without merging