Add Source Link to the sources
imartinez/privateGPT pull request #2036
Opened 2024-08-05 06:47 UTC by slale-91

# Description

This change does two things. The files to be used on the left-hand side are sorted alphabetically. This makes it easier to find the individual files you want to work with.

Furthermore, the variable USE_HYPERLINKS_FOR_SOURCES = TRUE can be used to refer to local sources via hyperlink.
BUG: Hyperlink is generated but cannot be clicked.

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [x ] I stared at the code and made sure it makes sense

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I ran `make check; make test` to ensure mypy and tests pass

2024-08-05 08:10 UTC, slale-91 commented
![image](https://github.com/user-attachments/assets/5e38ec09-3704-46ec-938c-635b1f2a97e1)

2024-08-06 14:11 UTC, jaluma requested changes

2024-08-06 14:11 UTC, jaluma commented on private_gpt/ui/ui.py
> +    pdf_prefix: str = "C:/UsedFilesFolder/"
you cannot assume that. You will need to store files in a folder in addition to current process

2024-08-06 14:11 UTC, jaluma commented on private_gpt/ui/ui.py
> +        file_path = f"{self.pdf_prefix}{encoded_file}#page={self.page}"
`#page` will only work when it's a doc and it's indexable (e.g. pdf)

2024-08-06 14:11 UTC, jaluma commented on private_gpt/ui/ui.py
> +                        if settings().USE_HYPERLINKS_FOR_SOURCES:
there is a ui setting object. The best idea is create a new filed in UI settings and create a boolean property

2024-08-06 14:11 UTC, jaluma commented on private_gpt/ui/ui.py
In general, you will need to do more than you might expect. Storing files in the local folder may not be trivial. If anything, please update the PR, ping me and we'll check it out :)

2026-05-29 10:52 UTC, AlfonsoLozana commented
Thank you for your contribution!
We consider this PR valuable, but we're doing a major update to the repository and unfortunately these changes no longer apply to the current codebase. For that reason, we're closing it, but please feel free to open it again over the new codebase, we'd love to review it there. 
We really appreciate the time and effort you put into this, and hope you'll continue being part of the project!

2026-05-29 10:52 UTC, closed without merging