Add fix for clang install of non m1 mac
imartinez/privateGPT pull request #231
Opened 2023-05-17 01:48 UTC by milescattini

2023-05-17 14:06 UTC, R-Y-M-R requested changes
Really good contribution for Mac users! Minor typo for you to fix. Thanks for the contribution!

2023-05-17 14:06 UTC, R-Y-M-R commented on README.md
> +When running a Mac with inteel hardware (not M1), you may run into _clang: error: the clang compiler does not support '-march=native'_ during pip install.
Small typo

2023-05-18 08:03 UTC, milescattini commented on README.md
> +When running a Mac with inteel hardware (not M1), you may run into _clang: error: the clang compiler does not support '-march=native'_ during pip install.
Ha! Whoops. Fixed.

2023-05-18 21:51 UTC, imartinez approved these changes
Thanks for this contribution helping the community!

2023-05-18 21:51 UTC, merged