fixed the the csv file reading issue
imartinez/privateGPT pull request #560
Opened 2023-05-30 18:42 UTC by ravindraprasad75

Original code was written by [GuySarkinsky](https://github.com/GuySarkinsky) in issue #448

2023-05-31 16:50 UTC, BaileyJM02 requested changes

2023-05-31 16:50 UTC, BaileyJM02 commented on ingest.py
> +        glob.glob(os.path.join(source_dir, f"**/*{ext}"), recursive=True)
The formatting on this line seems to have been edited by accident

```suggestion
            glob.glob(os.path.join(source_dir, f"**/*{ext}"), recursive=True)
```

2023-05-31 19:23 UTC, tylorschafer commented
I first noticed this issue last week. I was trying to import a Silicon Valley Episodes list .csv and noticed it only pulling the first episode from the list.

**Intake**
![main-intake](https://github.com/imartinez/privateGPT/assets/3358870/5757674b-8adb-4c47-ae05-6b76bf2beab2)
**Chat**
![main-chat](https://github.com/imartinez/privateGPT/assets/3358870/b2bef6e8-29c2-41a9-bbae-03faac7dfbf8)

I had tried the fix mentioned by Guy earlier and it worked. This branch has the same fix and works. Here are the results.
**Intake**
![Screenshot 2023-05-31 131645](https://github.com/imartinez/privateGPT/assets/3358870/cce42f3b-f5f8-45c8-96a8-85d27e943714)
**Chat**
![Screenshot 2023-05-31 131746](https://github.com/imartinez/privateGPT/assets/3358870/2b7986e1-25d9-4d20-bd74-962134475296)

2023-05-31 19:25 UTC, tylorschafer approved these changes

2023-06-01 08:25 UTC, imartinez approved these changes
Good catch!

2023-06-01 08:25 UTC, merged